name: Build APK Buildozer
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_args: android debug
          requirements: pygame
